# Generated by Django 4.2.3 on 2023-07-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviereviewapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='str', upload_to='gallery'),
        ),
    ]
